repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - args:
    - --fix=no
    id: mixed-line-ending
  - args:
    - --branch
    - master
    - --branch
    - develop
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
- hooks:
  - additional_dependencies:
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - markupsafe==2.1.1
    - pydantic==1.10.4
    - sqlalchemy==1.4.46
    - typing-extensions==4.4.0
    - werkzeug==2.2.2
    - sqlalchemy-stubs==0.4
    - types-PyYAML==6.0.12.3
    args:
    - --ignore-missing-imports
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v1.25.1
- hooks:
  - additional_dependencies:
    - flake8-print==3.1.4
    exclude: manage.py
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - exclude: manage.py
    id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
- hooks:
  - exclude: manage.py
    id: black
    language_version: python3.10
  repo: https://github.com/ambv/black
  rev: 22.3.0
- hooks:
  - id: codespell
  repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
